// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.
#pragma once

#include <frc2/command/SubsystemBase.h>
#include <frc/XboxController.h>
#include "frc/PneumaticHub.h"
#include "frc/Solenoid.h"
#include "frc/Compressor.h"
#include "Globals.h"

/**
 * RobotIntake subsystem header file
 *
 * @author 2826WaveRobotics
 */
class RobotIntake: public frc2::SubsystemBase 
{
    private:
        // It's desirable that everything possible is private except
        // for methods that implement subsystem capabilities

        // Pointer to the operator controller
        frc::XboxController *m_driverJoystick;

        frc::PneumaticHub m_pneumaticHub{k_pneumaticHub};
        frc::Compressor *m_compressor;

        // RobotIntake solenoid to deploy
        frc::Solenoid m_robotIntakeDeploySolenoid = m_pneumaticHub.MakeSolenoid(k_robotIntakeDeploy);

        // RobotIntake grabber solenoid to clamp and release robot bumper
        frc::Solenoid m_robotIntakeClampSolenoid = m_pneumaticHub.MakeSolenoid(k_robotIntakeClamp);

    public:
        RobotIntake();

        void robotIntakeClamp(bool isClamped);
        void robotIntakeDeploy(bool isDeployed);
        void runRobotIntake();

        void Initialize();
        void Periodic() override;
        void SimulationPeriodic() override;

};

