// // RobotBuilder Version: 5.0
// //
// // This file was generated by RobotBuilder. It contains sections of
// // code that are automatically generated and assigned by robotbuilder.
// // These sections will be updated in the future when you export to
// // C++ from RobotBuilder. Do not put any code or make any change in
// // the blocks indicating autogenerated code or it will be lost on an
// // update. Deleting the comments indicating the section will prevent
// // it from being updated in the future.

// // ROBOTBUILDER TYPE: SequentialCommandGroup.


// #pragma once

// #include <frc2/command/CommandHelper.h>
// #include <frc2/command/CommandBase.h>

// #include <frc2/command/SequentialCommandGroup.h>
// #include <frc/smartdashboard/SendableChooser.h>
// #include <frc2/command/Command.h>

// /**
//  *
//  *
//  * @author ExampleAuthor
//  */
// class CustomCommand: public frc2:: CommandHelper<frc2::SequentialCommandGroup,
// CustomCommand>{
// public:

//     explicit CustomCommand(frc::SendableChooser<frc2::Command*> commandChoosers[5]);

//     bool RunsWhenDisabled() const override;

// private:
//     frc::SendableChooser<frc2::Command*> m_choosers[5];
// };

