// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

#pragma once

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

#include <frc2/command/CommandHelper.h>
#include <frc2/command/CommandBase.h>
// #include <commands/WaveWaitCommand.h>
#include "subsystems/EndEffector.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 *
 *
 * @author ExampleAuthor
 */
class EndEffectorDown: public frc2::CommandHelper<frc2::CommandBase, EndEffectorDown> {
public:
    explicit EndEffectorDown(EndEffector* endEffector);

    void Initialize();
    void Execute();
    bool IsFinished();
    void End(bool interrupted);
    bool RunsWhenDisabled() const;


private:
    EndEffector* m_endEffector;
    // WaveWaitCommand* m_waitCommand;
    bool m_targetReached;
    // bool m_timerSet;
};