// // RobotBuilder Version: 5.0
// //
// // This file was generated by RobotBuilder. It contains sections of
// // code that are automatically generated and assigned by robotbuilder.
// // These sections will be updated in the future when you export to
// // C++ from RobotBuilder. Do not put any code or make any change in
// // the blocks indicating autogenerated code or it will be lost on an
// // update. Deleting the comments indicating the section will prevent
// // it from being updated in the future.

// // ROBOTBUILDER TYPE: SequentialCommandGroup.
// #include "commands/CustomCommand.h"
// #include <frc/smartdashboard/SendableChooser.h>
// #include <frc2/command/Command.h>

// #include "frc2/command/SequentialCommandGroup.h"

// CustomCommand::CustomCommand(frc::SendableChooser<frc2::Command*> commandChoosers[5])
// :m_choosers(commandChoosers)
// {
//     SetName("CustomCommand");

//     AddCommands(
//         frc2::SequentialCommandGroup
//         (
//             m_choosers[0].GetSelected(),
//             m_choosers[1].GetSelected(),
//             m_choosers[2].GetSelected(),
//             m_choosers[3].GetSelected(),
//             m_choosers[4].GetSelected()
//         )
//     );
// }

// bool CustomCommand::RunsWhenDisabled() const 
// {
//     return false;
// }