// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

#include "commands/DelayedScoreBackoff.h"
#include "commands/ExtendElevatorMidCone.h"
#include "commands/EndEffectorDown.h"
#include "commands/OpenGrabber.h"
#include "commands/WaveWaitCommand.h"
#include "commands/StowElevator.h"
#include "commands/ScoreBackoff.h"
#include "commands/EndEffectorUp.h"
#include "commands/ExtendElevatorBackoff.h"
// #include "frc2/command/ParallelCommandGroup.h"

DelayedScoreBackoff::DelayedScoreBackoff(Elevator* m_elevator)
:m_elevator(m_elevator)
{
    SetName("DelayedScoreBackoff");
    AddRequirements({m_elevator});

    AddCommands(
        frc2::SequentialCommandGroup
        (
            WaveWaitCommand(units::second_t(2.0)),
            ExtendElevatorBackoff(m_elevator)            
        )
    );
}

bool DelayedScoreBackoff::RunsWhenDisabled() const 
{
    return false;
}