// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

#include <iostream>
#include "commands/ElevatorHold.h"

ElevatorHold::ElevatorHold(Elevator* elevator)
: m_elevator(elevator), m_targetReached(false), m_timerSet(false)
{

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("ElevatorHold");
    AddRequirements({m_elevator});
}

// Called just before this Command runs the first time
void ElevatorHold::Initialize() 
{
    m_targetReached = false;
    m_timerSet = false;
    m_timer = 0;
}

// Called repeatedly when this Command is scheduled to run
void ElevatorHold::Execute() 
{
    if(!m_timerSet)
    {
        m_timer = 0;
        m_elevator->holdElevator();
        m_timerSet = true;
    }
    m_timer++;
    m_targetReached = (m_timer > ONE_SECOND);
}

// Make this return true when this Command no longer needs to run execute()
bool ElevatorHold::IsFinished() 
{
    return m_targetReached;
}

// Called once after isFinished returns true
void ElevatorHold::End(bool interrupted) 
{
    m_targetReached = false;
    m_timerSet = false;
    m_timer = 0;
}

bool ElevatorHold::RunsWhenDisabled() const 
{
    return false;
}