// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

#include <iostream>
#include "commands/OpenGrabber.h"

OpenGrabber::OpenGrabber(Elevator* m_elevator)
:m_elevator(m_elevator)
{    
    SetName("OpenGrabber");
    AddRequirements({m_elevator});
}

// Called just before this Command runs the first time
void OpenGrabber::Initialize() 
{

}

// Called repeatedly when this Command is scheduled to run
void OpenGrabber::Execute() 
{
    m_elevator->MoveGrabber(true);
}

// Make this return true when this Command no longer needs to run execute()
bool OpenGrabber::IsFinished() 
{
    return false;
}

// Called once after isFinished returns true
void OpenGrabber::End(bool interrupted) 
{
    
}

bool OpenGrabber::RunsWhenDisabled() const 
{
    return false;
}
