// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

#include "commands/SequentialScoreTopCone.h"
#include "commands/ExtendElevatorTopCone.h"
#include "commands/EndEffectorDown.h"
#include "commands/OpenGrabber.h"
#include "commands/WaveWaitCommand.h"
#include "commands/StowElevator.h"
#include "frc2/command/SequentialCommandGroup.h"

SequentialScoreTopCone::SequentialScoreTopCone(Elevator* m_elevator)
:m_elevator(m_elevator)
{
    SetName("SequentialScoreTopCone");
    AddRequirements({m_elevator});

    AddCommands(
        frc2::SequentialCommandGroup
        (
            ExtendElevatorTopCone(m_elevator),
            EndEffectorDown(m_elevator),
            OpenGrabber(m_elevator),
            WaveWaitCommand(units::second_t(1.0)),
            StowElevator(m_elevator)
        )
    );
}

bool SequentialScoreTopCone::RunsWhenDisabled() const 
{
    return false;
}