// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

#include "commands/SwerveInitializeCommand.h"

SwerveInitializeCommand::SwerveInitializeCommand(SwerveDrive* swerveDrive)
                      : m_swerveDrive(swerveDrive)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("SwerveInitializeCommand");
    AddRequirements(m_swerveDrive);

    m_isInitialized = false;
}

// Called just before this Command runs the first time
void SwerveInitializeCommand::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void SwerveInitializeCommand::Execute() {
    m_isInitialized = m_swerveDrive->InitialSwerve();
}

// Make this return true when this Command no longer needs to run execute()
bool SwerveInitializeCommand::IsFinished() {
    if (m_isInitialized) {
        return true;
    } else {
        return false;
    }
}

// Called once after isFinished returns true
void SwerveInitializeCommand::End(bool interrupted) {
    m_swerveDrive->DrivePods(0, 0, 0);
}

bool SwerveInitializeCommand::RunsWhenDisabled() const {
    return false;
}
