// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

#include "subsystems/Intake.h"
#include <frc/smartdashboard/SmartDashboard.h>

Intake::Intake(){
    SetName("Intake");
    SetSubsystem("Intake");

    // m_compressor = new frc::Compressor(k_pneumaticHub, frc::PneumaticsModuleType::REVPH);
    // m_pneumaticHub.EnableCompressorAnalog(units::pressure::pounds_per_square_inch_t(90), 
    //                                       units::pressure::pounds_per_square_inch_t(110));

}

// Put code here to be run every loop
void Intake::Periodic() {}

// This method will be called once per scheduler run when in simulation
void Intake::SimulationPeriodic() {}

// Put methods for controlling this subsystem
// here. Call these from Commands.
